##### **Sesión 23 - Programación para Ciencia de Datos 2026-1 - 22 Noviembre 2025**
---
# **Indexación, slicing y operaciones elementales**

Crear un notebook llamado `numpy_indexacion.ipynb` que contenga:
- Al menos 5 ejemplos distintos de slicing y máscaras booleanas.
- Comentarios explicando cada ejemplo.
- Comparación visual de resultados.

---
##### **Ejercicios:**

In [3]:
import numpy as np

print("=" * 60)
print("INDEXACION, SLICING Y MASCARAS BOOLEANAS EN NUMPY")
print("=" * 60)

# Crear arrays de ejemplo para los ejercicios
print("\nARRAYS DE EJEMPLO CREADOS:")

# Array 1D
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Array 1D: {arr_1d}")

# Array 2D
arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
print(f"Array 2D:\n{arr_2d}")

# Array con números aleatorios para máscaras booleanas
arr_random = np.random.randint(0, 100, 15)
print(f"Array aleatorio: {arr_random}")

print("\n" + "=" * 60)
print("1. SLICING BASICO EN ARRAY 1D")
print("=" * 60)

print("Array original:", arr_1d)

# Ejemplo 1: Slicing basico [start:stop:step]
print("\n--- Ejemplo 1: Slicing basico [2:7] ---")
slice_1 = arr_1d[2:7]
print("arr_1d[2:7] =", slice_1)
print("Explicacion: Toma elementos desde índice 2 hasta índice 6 (7 no incluido)")

# Ejemplo 2: Slicing con paso
print("\n--- Ejemplo 2: Slicing con paso [1:9:2] ---")
slice_2 = arr_1d[1:9:2]
print("arr_1d[1:9:2] =", slice_2)
print("Explicación: Toma elementos desde índice 1 hasta 8, saltando de 2 en 2")

# Ejemplo 3: Slicing desde el inicio o hasta el final
print("\n--- Ejemplo 3: Slicing con índices implícitos ---")
slice_3a = arr_1d[:4]    # Primeros 4 elementos
slice_3b = arr_1d[6:]    # Desde índice 6 hasta el final
slice_3c = arr_1d[::3]   # Todo el array con paso 3

print("arr_1d[:4] =", slice_3a, "← Primeros 4 elementos")
print("arr_1d[6:] =", slice_3b, "← Desde índice 6 hasta el final")
print("arr_1d[::3] =", slice_3c, "← Todo el array, paso 3")

print("\n" + "=" * 60)
print("2. SLICING EN ARRAY 2D")
print("=" * 60)

print("Array 2D original:")
print(arr_2d)

# Ejemplo 4: Slicing en 2D - filas y columnas
print("\n--- Ejemplo 4: Slicing de filas y columnas ---")
slice_4a = arr_2d[1:3, :]      # Filas 1 a 2, todas las columnas
slice_4b = arr_2d[:, 2:4]      # Todas las filas, columnas 2 a 3
slice_4c = arr_2d[0:2, 1:4]    # Filas 0 a 1, columnas 1 a 3

print("arr_2d[1:3, :] - Filas 1-2, todas columnas:")
print(slice_4a)

print("\narr_2d[:, 2:4] - Todas filas, columnas 2-3:")
print(slice_4b)

print("\narr_2d[0:2, 1:4] - Filas 0-1, columnas 1-3:")
print(slice_4c)

# Ejemplo 5: Slicing con pasos en 2D
print("\n--- Ejemplo 5: Slicing con pasos en 2D ---")
slice_5a = arr_2d[::2, :]      # Filas pares, todas columnas
slice_5b = arr_2d[:, ::2]      # Todas filas, columnas pares
slice_5c = arr_2d[::2, ::2]    # Filas y columnas pares

print("arr_2d[::2, :] - Filas pares (step 2), todas columnas:")
print(slice_5a)

print("\narr_2d[:, ::2] - Todas filas, columnas pares (step 2):")
print(slice_5b)

print("\narr_2d[::2, ::2] - Filas y columnas pares (step 2):")
print(slice_5c)

print("\n" + "=" * 60)
print("3. MÁSCARAS BOOLEANAS")
print("=" * 60)

print("Array aleatorio original:", arr_random)

# Ejemplo 6: Máscara básica - elementos mayores que 50
print("\n--- Ejemplo 6: Máscara para valores > 50 ---")
mask_1 = arr_random > 50
result_1 = arr_random[mask_1]
print("Máscara (arr_random > 50):", mask_1)
print("Elementos que cumplen la condición:", result_1)
print("Explicación: La máscara es un array booleano que selecciona solo los elementos True")

# Ejemplo 7: Múltiples condiciones
print("\n--- Ejemplo 7: Múltiples condiciones (20 <= x <= 70) ---")
mask_2 = (arr_random >= 20) & (arr_random <= 70)
result_2 = arr_random[mask_2]
print("Máscara ((arr_random >= 20) & (arr_random <= 70)):", mask_2)
print("Elementos entre 20 y 70:", result_2)

# Ejemplo 8: Condiciones OR y NOT
print("\n--- Ejemplo 8: Condiciones OR y valores pares ---")
mask_3 = (arr_random < 20) | (arr_random > 80)
mask_4 = arr_random % 2 == 0  # Números pares
result_3 = arr_random[mask_3]
result_4 = arr_random[mask_4]

print("Elementos < 20 OR > 80:", result_3)
print("Elementos pares:", result_4)

# Ejemplo 9: Máscaras en arrays 2D
print("\n--- Ejemplo 9: Máscaras en array 2D ---")
print("Array 2D original:")
print(arr_2d)

mask_2d = arr_2d > 10
result_2d = arr_2d[mask_2d]

print("\nMáscara (arr_2d > 10):")
print(mask_2d)
print("\nElementos del array 2D que son > 10:", result_2d)

# Ejemplo 10: Modificar elementos usando máscaras
print("\n--- Ejemplo 10: Modificación con máscaras ---")
arr_modifiable = arr_2d.copy()
print("Array copia antes de modificar:")
print(arr_modifiable)

# Cambiar todos los elementos pares a -1
mask_pares = arr_modifiable % 2 == 0
arr_modifiable[mask_pares] = -1

print("\nDespués de cambiar elementos pares a -1:")
print(arr_modifiable)

print("\n" + "=" * 60)
print("4. COMPARACIÓN VISUAL DE RESULTADOS")
print("=" * 60)

# Crear un array para demostración visual
arr_demo = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

print("Array de demostración:")
print(arr_demo)

print("\nCOMPARACIÓN DE DIFERENTES TÉCNICAS DE INDEXACIÓN:")

# Diferentes técnicas aplicadas al mismo array
print("\n1. Slicing central [1:4, 1:4]:")
central_slice = arr_demo[1:4, 1:4]
print(central_slice)

print("\n2. Máscara para números mayores a 10:")
mask_mayores_10 = arr_demo > 10
mayores_10_result = arr_demo[mask_mayores_10]
print("Elementos > 10:", mayores_10_result)

print("\n3. Combinación de slicing y máscara:")
combinado = arr_demo[::2, :]  # Filas pares
print("Filas pares del array:")
print(combinado)
mask_combinado = combinado % 2 == 0  # Elementos pares en esas filas
result_combinado = combinado[mask_combinado]
print("Elementos pares en filas pares:", result_combinado)

print("\n" + "=" * 60)
print("5. EJEMPLOS AVANZADOS")
print("=" * 60)

# Ejemplo avanzado 1: Indexación con arrays de índices
print("--- Ejemplo avanzado 1: Indexación con arrays de índices ---")
arr_avanzado = np.array([100, 200, 300, 400, 500, 600])
indices = np.array([0, 2, 4, 1, 5])  # Índices en orden específico
result_avanzado = arr_avanzado[indices]
print("Array:", arr_avanzado)
print("Índices:", indices)
print("Resultado con índices personalizados:", result_avanzado)

# Ejemplo avanzado 2: Máscara compleja con condiciones múltiples
print("\n--- Ejemplo avanzado 2: Máscara compleja ---")
arr_complejo = np.random.randint(0, 50, 20)
print("Array:", arr_complejo)

mask_compleja = (arr_complejo % 3 == 0) & (arr_complejo > 10) & (arr_complejo < 40)
result_complejo = arr_complejo[mask_compleja]

print("Máscara: (divisible por 3) Y (> 10) Y (< 40)")
print("Elementos que cumplen:", result_complejo)

# Ejemplo avanzado 3: Indexación fancy con arrays 2D
print("\n--- Ejemplo avanzado 3: Indexación fancy en 2D ---")
arr_fancy = np.arange(1, 26).reshape(5, 5)
print("Array 5x5:")
print(arr_fancy)

# Seleccionar elementos específicos usando coordenadas
filas = np.array([0, 2, 4])
columnas = np.array([1, 3, 0])
elementos_seleccionados = arr_fancy[filas, columnas]
print(f"Coordenadas: filas {filas}, columnas {columnas}")
print("Elementos seleccionados:", elementos_seleccionados)

print("\n" + "=" * 60)
print("RESUMEN Y CONCLUSIONES")
print("=" * 60)

print("""
RESUMEN DE TÉCNICAS:

SLICING:
- Sintaxis: [start:stop:step] para 1D, [filas, columnas] para 2D
- Útil para seleccionar rangos contiguos de elementos
- Eficiente para operaciones por bloques

MÁSCARAS BOOLEANAS:
- Sintaxis: array[condición]
- Útil para seleccionar elementos basados en condiciones
- Permite condiciones complejas con & (AND), | (OR), ~ (NOT)
- Ideal para filtrado de datos

INDEXACIÓN AVANZADA:
- Usando arrays de índices
- Indexación fancy con coordenadas
- Útil para selecciones no contiguas

VENTAJAS:
- Código más legible y conciso
- Operaciones vectorizadas (rápidas)
- Fácil manipulación de subconjuntos de datos

USOS COMUNES:
- Procesamiento de imágenes (ROI - Region of Interest)
- Filtrado de datos en ciencia de datos
- Selección de elementos específicos en arrays grandes
- Operaciones condicionales en matrices
""")

# Demostración final comparativa CORREGIDA
print("\nDEMOSTRACIÓN FINAL COMPARATIVA:")
arr_final = np.arange(1, 26).reshape(5, 5)
print("Array final 5x5:")
print(arr_final)

print("\nDiferentes formas de seleccionar elementos:")

# Método 1: Slicing para obtener submatriz
print("\n1. Submatriz central [1:4, 1:4]:")
submatriz = arr_final[1:4, 1:4]
print(submatriz)

# Método 2: Fila y columna central por separado
print("\n2. Fila y columna central por separado:")
fila_central = arr_final[2, :]
columna_central = arr_final[:, 2]
print("Fila central [2, :]:", fila_central)
print("Columna central [:, 2]:", columna_central)

# Método 3: Máscara para elementos en esquinas
print("\n3. Elementos de las esquinas usando máscara:")
# Crear máscara para esquinas
mascara_esquinas = np.zeros((5, 5), dtype=bool)
mascara_esquinas[0, 0] = True  # Esquina superior izquierda
mascara_esquinas[0, 4] = True  # Esquina superior derecha
mascara_esquinas[4, 0] = True  # Esquina inferior izquierda
mascara_esquinas[4, 4] = True  # Esquina inferior derecha

esquinas = arr_final[mascara_esquinas]
print("Esquinas del array:", esquinas)

# Método 4: Combinación de técnicas
print("\n4. Combinación: elementos pares en el borde exterior:")
borde_superior = arr_final[0, :]
borde_inferior = arr_final[4, :]
borde_izquierdo = arr_final[1:4, 0]
borde_derecho = arr_final[1:4, 4]

# Combinar todos los bordes y filtrar pares
todos_bordes = np.concatenate([borde_superior, borde_inferior, borde_izquierdo, borde_derecho])
pares_en_borde = todos_bordes[todos_bordes % 2 == 0]
print("Elementos pares en el borde exterior:", pares_en_borde)

print("\n" + "=" * 60)
print("COMPARACIÓN FINAL DE TÉCNICAS")
print("=" * 60)

print("""
SINTAXIS COMPARATIVA:

SLICING:      arr[inicio:fin:paso]
MÁSCARAS:     arr[condición]
ÍNDICES:      arr[[índice1, índice2, ...]]
COORDENADAS:  arr[filas, columnas]

CARACTERÍSTICAS:
- Slicing: Mejor para rangos contiguos
- Máscaras: Mejor para selección condicional  
- Índices: Mejor para posiciones específicas
- Coordenadas: Mejor para patrones complejos

RECOMENDACIONES:
- Usar slicing para bloques rectangulares
- Usar máscaras para filtrado por condiciones
- Usar indexación fancy para patrones irregulares
- Combinar técnicas para casos complejos
""")

INDEXACION, SLICING Y MASCARAS BOOLEANAS EN NUMPY

ARRAYS DE EJEMPLO CREADOS:
Array 1D: [ 10  20  30  40  50  60  70  80  90 100]
Array 2D:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Array aleatorio: [ 2 36 81 84 67 17 59 41 12 81 81 46 48 12  8]

1. SLICING BASICO EN ARRAY 1D
Array original: [ 10  20  30  40  50  60  70  80  90 100]

--- Ejemplo 1: Slicing basico [2:7] ---
arr_1d[2:7] = [30 40 50 60 70]
Explicacion: Toma elementos desde índice 2 hasta índice 6 (7 no incluido)

--- Ejemplo 2: Slicing con paso [1:9:2] ---
arr_1d[1:9:2] = [20 40 60 80]
Explicación: Toma elementos desde índice 1 hasta 8, saltando de 2 en 2

--- Ejemplo 3: Slicing con índices implícitos ---
arr_1d[:4] = [10 20 30 40] ← Primeros 4 elementos
arr_1d[6:] = [ 70  80  90 100] ← Desde índice 6 hasta el final
arr_1d[::3] = [ 10  40  70 100] ← Todo el array, paso 3

2. SLICING EN ARRAY 2D
Array 2D original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

--- E