##### **Sesión 22 - Programación para Ciencia de Datos 2026-1 - 21 Noviembre 2025**
---
# **Introducción a NumPy y creación de arrays**

Crear un notebook llamado `numpy_arrays.ipynb` que incluya: 
- Ejemplos de creación de arrays con distintas funciones.
- Comparaciones con listas.
- Uso de propiedades (shape, size, ndim, dtype).

---
##### **Ejercicios:**

In [2]:
import numpy as np
import time
import sys

# 1. CREACION DE ARRAYS CON DIFERENTES FUNCIONES

print("=" * 50)
print("1. CREACION DE ARRAYS")
print("=" * 50)

# a) np.zeros - Crea un array lleno de ceros
print("\nnp.zeros - Arrays llenos de ceros:")
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3, 4))
zeros_3d = np.zeros((2, 3, 2))

print(f"1D: {zeros_1d}")
print(f"2D:\n{zeros_2d}")
print(f"3D shape: {zeros_3d.shape}")

# b) np.ones - Crea un array lleno de unos
print("\nnp.ones - Arrays llenos de unos:")
ones_1d = np.ones(5)
ones_2d = np.ones((2, 3))
ones_with_dtype = np.ones(4, dtype=np.int32)

print(f"1D: {ones_1d}")
print(f"2D:\n{ones_2d}")
print(f"Con dtype int32: {ones_with_dtype}")

# c) np.arange - Similar a range() pero para arrays
print("\nnp.arange - Secuencias numericas:")
arange_simple = np.arange(10)
arange_start_stop = np.arange(5, 15)
arange_step = np.arange(0, 20, 3)
arange_float = np.arange(0, 2, 0.3)

print(f"0-9: {arange_simple}")
print(f"5-14: {arange_start_stop}")
print(f"0-19 paso 3: {arange_step}")
print(f"0-2 paso 0.3: {arange_float}")

# d) np.linspace - Secuencias con numero especifico de puntos
print("\nnp.linspace - Puntos equiespaciados:")
linspace_simple = np.linspace(0, 10, 5)
linspace_no_endpoint = np.linspace(0, 10, 5, endpoint=False)
linspace_2d = np.linspace(0, 1, 6).reshape(2, 3)

print(f"0-10 con 5 puntos: {linspace_simple}")
print(f"0-10 con 5 puntos (sin incluir 10): {linspace_no_endpoint}")
print(f"2D shape:\n{linspace_2d}")

# 2. COMPARACIONES CON LISTAS (TIEMPO/EFICIENCIA)

print("\n" + "=" * 50)
print("2. COMPARACION ARRAYS vs LISTAS")
print("=" * 50)

# Tamaño para las pruebas
size = 1000000

# Comparación de memoria
print("\nCOMPARACION DE MEMORIA:")
lista = list(range(size))
array_numpy = np.arange(size)

memoria_lista = sys.getsizeof(lista)
memoria_array = sys.getsizeof(array_numpy) + array_numpy.nbytes

print(f"Memoria lista: {memoria_lista / 1024 / 1024:.2f} MB")
print(f"Memoria array NumPy: {memoria_array / 1024 / 1024:.2f} MB")
print(f"Ratio memoria (lista/array): {memoria_lista/memoria_array:.2f}x")

# Comparación de tiempo para operaciones matematicas
print("\nCOMPARACION DE TIEMPO - OPERACIONES MATEMATICAS:")

# Operación con lista
start_time = time.time()
resultado_lista = [x * 2 + 5 for x in lista]
tiempo_lista = time.time() - start_time

# Operación con array NumPy
start_time = time.time()
resultado_array = array_numpy * 2 + 5
tiempo_array = time.time() - start_time

print(f"Tiempo lista: {tiempo_lista:.6f} segundos")
print(f"Tiempo array NumPy: {tiempo_array:.6f} segundos")

# Evitar division por cero
if tiempo_array > 0:
    print(f"Array es {tiempo_lista/tiempo_array:.1f}x mas rapido")
else:
    print("Array es extremadamente rapido (tiempo casi cero)")

# Comparación de suma de elementos
print("\nCOMPARACION DE TIEMPO - SUMA DE ELEMENTOS:")

# Suma con lista
start_time = time.time()
suma_lista = sum(lista)
tiempo_suma_lista = time.time() - start_time

# Suma con array NumPy
start_time = time.time()
suma_array = np.sum(array_numpy)
tiempo_suma_array = time.time() - start_time

print(f"Tiempo suma lista: {tiempo_suma_lista:.6f} segundos")
print(f"Tiempo suma array: {tiempo_suma_array:.6f} segundos")

if tiempo_suma_array > 0:
    print(f"Array es {tiempo_suma_lista/tiempo_suma_array:.1f}x mas rapido")
else:
    print("Array es extremadamente rapido en sumas")

# 3. USO DE PROPIEDADES DE ARRAYS

print("\n" + "=" * 50)
print("3. PROPIEDADES DE ARRAYS")
print("=" * 50)

# Crear un array de ejemplo para demostrar propiedades
array_ejemplo = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

print("Array de ejemplo:")
print(array_ejemplo)

# Propiedades principales
print("\nPROPIEDADES DEL ARRAY:")

# shape - Dimensiones del array
print(f"shape: {array_ejemplo.shape}")
print("   (filas, columnas, profundidad)")

# size - Numero total de elementos
print(f"size: {array_ejemplo.size}")
print(f"   (3 x 2 x 3 = {3*2*3} elementos)")

# ndim - Numero de dimensiones
print(f"ndim: {array_ejemplo.ndim}")
print("   (3 dimensiones)")

# dtype - Tipo de datos
print(f"dtype: {array_ejemplo.dtype}")
print("   (tipo de datos de los elementos)")

# Ejemplos adicionales con diferentes arrays
print("\n" + "=" * 50)
print("EJEMPLOS ADICIONALES")
print("=" * 50)

# Array 1D
array_1d = np.array([1, 2, 3, 4, 5])
print(f"\nArray 1D: {array_1d}")
print(f"Shape: {array_1d.shape}, Size: {array_1d.size}, ndim: {array_1d.ndim}")

# Array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\nArray 2D:\n{array_2d}")
print(f"Shape: {array_2d.shape}, Size: {array_2d.size}, ndim: {array_2d.ndim}")

# Array con diferentes tipos de datos
array_float = np.array([1.5, 2.7, 3.1], dtype=np.float64)
array_int = np.array([1, 2, 3], dtype=np.int32)
array_bool = np.array([True, False, True])

print(f"\nTipos de datos:")
print(f"Float64: {array_float.dtype}")
print(f"Int32: {array_int.dtype}")
print(f"Bool: {array_bool.dtype}")


1. CREACION DE ARRAYS

np.zeros - Arrays llenos de ceros:
1D: [0. 0. 0. 0. 0.]
2D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3D shape: (2, 3, 2)

np.ones - Arrays llenos de unos:
1D: [1. 1. 1. 1. 1.]
2D:
[[1. 1. 1.]
 [1. 1. 1.]]
Con dtype int32: [1 1 1 1]

np.arange - Secuencias numericas:
0-9: [0 1 2 3 4 5 6 7 8 9]
5-14: [ 5  6  7  8  9 10 11 12 13 14]
0-19 paso 3: [ 0  3  6  9 12 15 18]
0-2 paso 0.3: [0.  0.3 0.6 0.9 1.2 1.5 1.8]

np.linspace - Puntos equiespaciados:
0-10 con 5 puntos: [ 0.   2.5  5.   7.5 10. ]
0-10 con 5 puntos (sin incluir 10): [0. 2. 4. 6. 8.]
2D shape:
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]

2. COMPARACION ARRAYS vs LISTAS

COMPARACION DE MEMORIA:
Memoria lista: 7.63 MB
Memoria array NumPy: 15.26 MB
Ratio memoria (lista/array): 0.50x

COMPARACION DE TIEMPO - OPERACIONES MATEMATICAS:
Tiempo lista: 0.356402 segundos
Tiempo array NumPy: 0.011985 segundos
Array es 29.7x mas rapido

COMPARACION DE TIEMPO - SUMA DE ELEMENTOS:
Tiempo suma lista: 0.078961 segundos
Tiempo su